version: '3'

services:
  web:
    restart: always
    build: ./src
    expose:
      - '8000'
    #links:
      #- postgres:postgres
      #- redis:redis
    volumes:
      - "./src:/usr/src/eusou"
      #- web-static:/usr/src/app/static
    env_file: .env-vars
    environment:
      DEBUG: 'true'
    command: gunicorn eusou.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - "./src/static:/www/static"
      #- web-static:/www/static
    links:
      - web:web

#volumes:
#  web-django:
#  web-static:
